name: chess_zero
channels:
  - menpo
  - soumith
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - pandas
  - h5py
  - scikit-learn<=0.20
  - tensorflow==1.3.0
  - pip:
    - keras==2.1.3
    - profilehooks
    - pyperclip
    - python-chess
